### PR TITLE
Add announce instead of tmi.say

### PR DESCRIPTION
**Pull request by ricardodevries**
This returns the usage of twitch annoucement messages in chat that were removed in b35976c4cc45f674ea340fc8aaa015b8d1312f26.

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Do you wanna merge in main (now #88 is merged) and then go wild with adding some colours to the announcements?

**Comment by ricardodevries** [comment]
Whatever works best for you.

This has been based on b35976c4cc45f674ea340fc8aaa015b8d1312f26. If the color is set to primary or is not set (as the case is with this pull request), the channel’s accent color is used to highlight the announcement. I am not sure if you want other tmi.say's to be announcements. Commit againsts this branch and then merge as desired.

**Comment by jwalter** [comment]
I didn't mean to push directly to upstream like that, sorry. Announce worked fine but did not interact well with the token/retry I implemented earlier so I wanted to have a fix ready to go for that but I guess it's ok to include it here?

**Review by whitep4nth3r — APPROVED** [review]
@jwalter switched out your post request for the helper he wrote to make it work 😅 and I added some colours.

Thanks for doing the initial legwork!

**Pull request merged**
