### PR TITLE
Added a check for giveaway winner in chat

### PR DESCRIPTION
**Pull request by amazinglySK**
Added a check to the draw function using the existing getCurrentChatters function 

Hope it helps !!

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
The only thing I think is missing is needing to await Giveaway.draw() when it is called!

**Comment by amazinglySK** [comment]
Hi WP. Did you mean the send

**Comment by amazinglySK** [comment]
@whitep4nth3r did you mean to await the sendGiveawayDrawEvent? Since I searched for instances of Giveaway.drop() and found none. Sorry if this question doesn't make sense.

**Comment by whitep4nth3r** [comment]
@amazinglySK It's Giveaway.drop() either in commands.ts or messages.ts :)

**Comment by amazinglySK** [comment]
Got it. Will commit it right away. Thank you so much :)

**Comment by whitep4nth3r** [comment]
Thank you! I'll merge this and we can test it in the Discord :)

**Pull request merged**
